title: "aitl-animation-demos"
description: "Experimental animation demos related to AITL concepts."
lang: en

url: "https://samizo-aitl.github.io"
baseurl: "/aitl-animation-demos"

theme: null   # ← 最重要（Minima を殺す）
remote_theme: null

markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter: rouge
  math_engine: mathjax
